"""
Generate the Phase-A (geometry-adaptive probe) configs from the 25deg base.

Phase A evaluates the CURRENT
checkpoint zero-shot on three new geometries with exact DC. This script writes,
per geometry:

  configs/leap_dbt_phaseA_<tag>.cfg   LEAP geometry (explicit SYMMETRIC
                                      proj_phis: -arc/2 ... +arc/2 -- settles
                                      the 0-anchored-arc review item for all
                                      new data; the legacy 25deg data keeps its
                                      LEAP-default convention)
  configs/dbt_phaseA_<tag>.yaml       evaluate.py config derived from
                                      configs/dbt_25deg.yaml with per-geometry
                                      data dir / results dir / operator npz

The generated files are committed; re-run this script only to regenerate them
after changing the base config or the geometry list.

    python scripts/make_phase_a_configs.py [--base configs/dbt_25deg.yaml]
"""

import argparse
import copy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# (tag, n_views, arc_degrees) -- rich / mid / sparse probe points, anchoring
# the pilot grid corners.
GEOMETRIES = [
    ("05v15", 5, 15.0),
    ("13v35", 13, 35.0),
    ("25v50", 25, 50.0),
]


def symmetric_phis(n_views: int, arc: float) -> list:
    """n_views angles spanning [-arc/2, +arc/2] inclusive, symmetric about 0."""
    if n_views == 1:
        return [0.0]
    step = arc / (n_views - 1)
    return [-arc / 2.0 + i * step for i in range(n_views)]


def write_leap_cfg(base_cfg: Path, out_cfg: Path, n_views: int, arc: float):
    """Copy the base LEAP cfg, overriding the angular geometry keys."""
    phis = symmetric_phis(n_views, arc)
    phis_str = ", ".join(f"{p:.6f}" for p in phis)
    overrides = {
        "proj_arange": f"{arc:g}",
        "proj_nangles": str(n_views),
        "proj_phis": phis_str,
    }
    lines = []
    for line in base_cfg.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            continue  # drop the base's header comments (they name 9p25d)
        key = stripped.partition("=")[0].strip() if "=" in stripped else None
        if key in overrides:
            lines.append(f"{key} = {overrides.pop(key)}")
        else:
            lines.append(line)
    assert not overrides, f"keys not found in {base_cfg}: {list(overrides)}"
    header = (
        f"# GENERATED by scripts/make_phase_a_configs.py -- Phase-A probe geometry\n"
        f"# {n_views:g}p{arc:g}d, SYMMETRIC arc "
        f"(proj_phis = -{arc/2:g} ... +{arc/2:g})\n"
    )
    out_cfg.write_text(header + "\n".join(lines) + "\n")


def write_yaml(base_yaml: Path, out_yaml: Path, tag: str, n_views: int, arc: float,
               leap_cfg: str = None, operator_npz: str = None):
    cfg = yaml.safe_load(base_yaml.read_text())
    cfg = copy.deepcopy(cfg)
    cfg["data"]["processed_dir"] = f"dataset/processed_phaseA_{tag}"
    cfg["data"]["split_file"] = "dataset/split_phaseA.json"
    cfg["geometry"]["leap_cfg"] = leap_cfg or f"configs/leap_dbt_phaseA_{tag}.cfg"
    cfg["geometry"]["angle_range"] = arc
    cfg["geometry"]["num_projections"] = n_views
    cfg["sampling"]["operator_npz"] = (operator_npz
                                       or f"runs/operator/A_phaseA_{tag}_512.npz")
    cfg["evaluation"]["results_dir"] = f"results/dbt_phaseA_{tag}"
    header = (
        f"# GENERATED by scripts/make_phase_a_configs.py from {base_yaml.name}.\n"
        f"# Phase-A probe geometry: {n_views:g}p{arc:g}d, symmetric arc.\n"
        f"# Only data/geometry/operator/results paths differ from the base;\n"
        f"# model/training/sampling sections are inherited verbatim.\n"
    )
    out_yaml.write_text(header + yaml.safe_dump(cfg, sort_keys=False))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", default=str(ROOT / "configs" / "dbt_25deg.yaml"))
    ap.add_argument("--base_leap", default=str(ROOT / "configs" / "leap_dbt_25deg.cfg"))
    args = ap.parse_args()

    for tag, n_views, arc in GEOMETRIES:
        leap_out = ROOT / "configs" / f"leap_dbt_phaseA_{tag}.cfg"
        yaml_out = ROOT / "configs" / f"dbt_phaseA_{tag}.yaml"
        write_leap_cfg(Path(args.base_leap), leap_out, n_views, arc)
        write_yaml(Path(args.base), yaml_out, tag, n_views, arc)
        print(f"[{tag}] wrote {leap_out.name} + {yaml_out.name} "
              f"({n_views} views / {arc:g} deg)")

    # 9/25deg ANCHOR: the same phantom subset + fast-path eval settings at the
    # production geometry, so the Phase-A geometry curve has an in-distribution
    # reference point measured under identical conditions. Reuses the ORIGINAL
    # (0-anchored) leap cfg and the production operator npz -- deliberately NOT
    # the symmetric convention, to stay the same operator family as the
    # production campaign (never mix operator families in one comparison).
    write_yaml(Path(args.base), ROOT / "configs" / "dbt_phaseA_09v25.yaml",
               "09v25", 9, 25.0,
               leap_cfg="configs/leap_dbt_25deg.cfg",
               operator_npz="runs/operator/A_25deg_512.npz")
    print("[09v25] wrote dbt_phaseA_09v25.yaml (anchor: original cfg + "
          "production operator)")


if __name__ == "__main__":
    main()
